baseURL = 'https://iot-systems-unsw.github.io/'
languageCode = 'en-us'
title = 'IoT Systems UNSW'
theme = 'research_group'
theme_url = 'https://github.com/mattrobball/hugo_research_group/'
relativeURLs = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Team"
    url = "/team/"
    weight = 2
  [[menu.nav]]
    name = "News"
    url = "/news/"
    weight = 3
  [[menu.nav]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.nav]]
    name = "Contact"
    url = "/contact/"
    weight = 5



[params]
  author = "IoT Systems UNSW"
  description = "Website for the IoT Systems research group at UNSW"
  logo = "/images/logo.png"
  images = ["/images/site-feature-image.jpg"]
  
  # Organization details
  organization_name = "IoT Systems UNSW"
  organization_full_name = "IoT Systems Research Group at UNSW"
  
  # Address information
  address_line1 = "School of Computer Science and Engineering"
  address_line2 = "University of New South Wales"
  address_line3 = "Sydney NSW 2052, Australia"
  address_map_link = "https://goo.gl/maps/example"
  
  # Copyright
  copyright_text = "IoT Systems Research Group at UNSW"

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[caches]
  [caches.images]
    dir = ':cacheDir/images'